# Generated by Django 3.2.8 on 2021-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, null=True, unique=True)),
                ('display_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('spotify_id', models.CharField(max_length=150, null=True, unique=True)),
                ('spotify_href', models.CharField(max_length=200, null=True, unique=True)),
                ('spotify_uri', models.CharField(max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
