# Generated by Django 3.2.8 on 2021-10-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
