# Generated by Django 3.2.8 on 2021-11-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_user_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
