# Generated by Django 3.2.8 on 2021-11-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_remove_user_no_of_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_visits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
