# Generated by Django 3.2.8 on 2021-11-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_user_no_of_visits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
