# Generated by Django 3.2.8 on 2021-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_song_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
